apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template: 
    metadata:
      labels:
         app: backend
    spec:
      containers:
      - name: bonfire-backend 
        image: gcr.io/bonfire-adventures-339612/bonfire-backend:0.1.4
        ports: 
          - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: database-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: database-secrets
              key: db_password
        - name: DB_NAME
          valueFrom: 
            secretKeyRef:
              name: database-secrets
              key: db_name
        - name: DB_HOST
          valueFrom: 
            secretKeyRef:
              name: database-secrets
              key: db_host
        